!*==info1.f90 processed by SPAG 8.04RA 23:24 22 Feb 2024
!!SPAG Open source Personal, Educational or Academic User Clemson University  NON-COMMERCIAL USE - Not for use on proprietary or closed source code
PROGRAM info1
!----------------------------------------------------------------------
! usage    info1.ex < HB_file
!
! where info1 is the executable generated by makefile, HB_file is a
! file containing a matrix stored in Harwell-Boeing matrices.
! Info1 will then dump the information into the standard output.
!
! To use with larger matrices, increase nmax and nzmax.
!----------------------------------------------------------------------
   USE ISO_FORTRAN_ENV                 
   IMPLICIT NONE
!
! PARAMETER definitions rewritten by SPAG
!
   INTEGER , PARAMETER :: NMAX = 30000 , NZMAX = 800000
!
! Local variable declarations rewritten by SPAG
!
   REAL(REAL64) , DIMENSION(NZMAX) :: a , a1
   CHARACTER(2) :: guesol
   INTEGER , DIMENSION(NMAX+1) :: ia , ia1
   INTEGER :: ierr , job , ncol , nnz , nrhs , nrow
   INTEGER , SAVE :: iin , iout
   INTEGER , DIMENSION(NZMAX) :: ja , ja1
   CHARACTER(8) :: key
   REAL(REAL64) , DIMENSION(1) :: rhs
   CHARACTER(72) :: title
   CHARACTER(3) :: type
   LOGICAL :: valued
   EXTERNAL dinfo1 , readmt
!
! End of declarations rewritten by SPAG
!
!
!--------------
   DATA iin/5/ , iout/6/
!--------------
   job = 2
   nrhs = 0
   CALL readmt(NMAX,NZMAX,job,iin,a,ja,ia,rhs,nrhs,guesol,nrow,ncol,nnz,title,key,type,ierr)
!---- if not readable return
   IF ( ierr/=0 ) THEN
      WRITE (iout,99001) ierr
99001 FORMAT (' **ERROR: Unable to read matrix',/,' Message returned fom readmt was ierr =',i3)
      STOP
   ENDIF
   valued = (job>=2)
!-------
   CALL dinfo1(ncol,iout,a,ja,ia,valued,title,key,type,a1,ja1,ia1)
!--------------------end------------------------------------------------
!-----------------------------------------------------------------------
END PROGRAM info1
